title: RichardTam's Homepage
page-top-title: 谭力玮
top-section-bg-text: Talk is cheap,show me the code.
home-subtitle: 谭力玮&ensp;|&ensp;RichardTam
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
